author: Isaac FEI
execute:
  execute_notebooks: force
html:
  favicon: logo.png
  use_issues_button: true
  use_repository_button: true
launch_buttons:
  colab_url: https://colab.research.google.com
  thebe: true
logo: logo.png
repository:
  branch: master
  url: https://github.com/Isaac-Fate/mathematical-analysis
sphinx:
  config:
    bibtex_reference_style: author_year
    mathjax_config:
      tex:
        macros:
          C: \mathbb{C}
          FF: \mathbb{F}
          N: \mathbb{N}
          Ns: \mathbb{N^\ast}
          Q: \mathbb{Q}
          R: \mathbb{R}
          Span:
          - \mathop{\mathrm{span}}
          Z: \mathbb{Z}
          abs:
          - '\left\lvert #1 \right\rvert'
          - 1
          argmax:
          - \mathop{\mathrm{arg \, max}}
          argmin:
          - \mathop{\mathrm{arg \, min}}
          bmat:
          - \left[\begin{array}
          col:
          - \mathop{\mathrm{col}}
          d:
          - \mathrm{d}
          emat:
          - \end{array}\right]
          floor:
          - \lfloor#1\rfloor
          - 1
          im:
          - \mathop{\mathrm{im}}
          ind:
          - \mathbb{1}
          ker:
          - \mathop{\mathrm{ker}}
          lowint:
          - \underline{\int}
          norm:
          - '\left\lVert #1 \right\rVert'
          - 1
          row:
          - \mathop{\mathrm{row}}
          set:
          - '\left\{ #1 \middle| #2 \right\}'
          - 2
          upint:
          - \overline{\int}
          v:
          - \mathbf{#1}
          - 1
  extra_extensions:
  - sphinx_proof
title: Mathematical Analysis
